- name: Wait for server availability
  wait_for_connection:
          timeout: 600

- name: Update apt cache
  apt:
          update_cache: yes

- name: apt dist upgrade
  apt:
          upgrade: dist

- name: Reboot server
  shell: "sleep 5 && shutdown -r now"
  async: 10
  poll: 0
  when: reboot_after_update

- name: Wait for server to reboot
  wait_for_connection:
          delay: 60
          timeout: 600
  when: reboot_after_update

- name: Install packages to enable HTTPS repositories
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present

- name: Install common packages
  apt:
    name:
      - git
      - neovim
      - tmux
      - tree
      - python3-pip
      - virtualenv
    state: present
